/* 
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: 2020-07-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FulfillmentAction : Specifies whether the fulfillment order should ship now or have an order hold put on it.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FulfillmentAction {
}

impl FulfillmentAction {
  /// Specifies whether the fulfillment order should ship now or have an order hold put on it.
  pub fn new() -> FulfillmentAction {
    FulfillmentAction {
    }
  }

}

// TODO enum 
// List of FulfillmentAction
//const (
//  
//  
//  
//)


