/* 
 * Selling Partner API for Retail Procurement Transaction Status
 *
 * The Selling Partner API for Retail Procurement Transaction Status provides programmatic access to status information on specific asynchronous POST transactions for vendors.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetTransactionResponse : The response schema for the getTransaction operation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetTransactionResponse {
  /// The response payload for the getTransaction operation.
  #[serde(rename = "payload")]
  payload: Option<::models::TransactionStatus>,
  #[serde(rename = "errors")]
  errors: Option<::models::ErrorList>
}

impl GetTransactionResponse {
  /// The response schema for the getTransaction operation.
  pub fn new() -> GetTransactionResponse {
    GetTransactionResponse {
      payload: None,
      errors: None
    }
  }

  pub fn set_payload(&mut self, payload: ::models::TransactionStatus) {
    self.payload = Some(payload);
  }

  pub fn with_payload(mut self, payload: ::models::TransactionStatus) -> GetTransactionResponse {
    self.payload = Some(payload);
    self
  }

  pub fn payload(&self) -> Option<&::models::TransactionStatus> {
    self.payload.as_ref()
  }

  pub fn reset_payload(&mut self) {
    self.payload = None;
  }

  pub fn set_errors(&mut self, errors: ::models::ErrorList) {
    self.errors = Some(errors);
  }

  pub fn with_errors(mut self, errors: ::models::ErrorList) -> GetTransactionResponse {
    self.errors = Some(errors);
    self
  }

  pub fn errors(&self) -> Option<&::models::ErrorList> {
    self.errors.as_ref()
  }

  pub fn reset_errors(&mut self) {
    self.errors = None;
  }

}



