/* 
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;
use std::borrow::Cow;
use std::collections::HashMap;

use hyper;
use serde_json;
use futures;
use futures::{Future, Stream};

use hyper::header::UserAgent;

use super::{Error, configuration};

pub struct VendorShippingLabelsApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> VendorShippingLabelsApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> VendorShippingLabelsApiClient<C> {
        VendorShippingLabelsApiClient {
            configuration: configuration,
        }
    }
}

pub trait VendorShippingLabelsApi {
    fn get_shipping_label(&self, purchase_order_number: &str) -> Box<Future<Item = ::models::GetShippingLabelResponse, Error = Error<serde_json::Value>>>;
    fn get_shipping_labels(&self, created_after: String, created_before: String, ship_from_party_id: &str, limit: i32, sort_order: &str, next_token: &str) -> Box<Future<Item = ::models::GetShippingLabelListResponse, Error = Error<serde_json::Value>>>;
    fn submit_shipping_label_request(&self, body: ::models::SubmitShippingLabelsRequest) -> Box<Future<Item = ::models::SubmitShippingLabelsResponse, Error = Error<serde_json::Value>>>;
}


impl<C: hyper::client::Connect>VendorShippingLabelsApi for VendorShippingLabelsApiClient<C> {
    fn get_shipping_label(&self, purchase_order_number: &str) -> Box<Future<Item = ::models::GetShippingLabelResponse, Error = Error<serde_json::Value>>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query_string = {
            let mut query = ::url::form_urlencoded::Serializer::new(String::new());
            query.finish()
        };
        let uri_str = format!("{}/vendor/directFulfillment/shipping/v1/shippingLabels/{purchaseOrderNumber}?{}", configuration.base_path, query_string, purchaseOrderNumber=purchase_order_number);

        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut uri: hyper::Uri = uri_str.parse().unwrap();

        let mut req = hyper::Request::new(method, uri);

        if let Some(ref user_agent) = configuration.user_agent {
            req.headers_mut().set(UserAgent::new(Cow::Owned(user_agent.clone())));
        }




        // send request
        Box::new(
        configuration.client.request(req)
            .map_err(|e| Error::from(e))
            .and_then(|resp| {
                let status = resp.status();
                resp.body().concat2()
                    .and_then(move |body| Ok((status, body)))
                    .map_err(|e| Error::from(e))
            })
            .and_then(|(status, body)| {
                if status.is_success() {
                    Ok(body)
                } else {
                    Err(Error::from((status, &*body)))
                }
            })
            .and_then(|body| {
                let parsed: Result<::models::GetShippingLabelResponse, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            })
        )
    }

    fn get_shipping_labels(&self, created_after: String, created_before: String, ship_from_party_id: &str, limit: i32, sort_order: &str, next_token: &str) -> Box<Future<Item = ::models::GetShippingLabelListResponse, Error = Error<serde_json::Value>>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query_string = {
            let mut query = ::url::form_urlencoded::Serializer::new(String::new());
            query.append_pair("shipFromPartyId", &ship_from_party_id.to_string());
            query.append_pair("limit", &limit.to_string());
            query.append_pair("createdAfter", &created_after.to_string());
            query.append_pair("createdBefore", &created_before.to_string());
            query.append_pair("sortOrder", &sort_order.to_string());
            query.append_pair("nextToken", &next_token.to_string());
            query.finish()
        };
        let uri_str = format!("{}/vendor/directFulfillment/shipping/v1/shippingLabels?{}", configuration.base_path, query_string);

        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut uri: hyper::Uri = uri_str.parse().unwrap();

        let mut req = hyper::Request::new(method, uri);

        if let Some(ref user_agent) = configuration.user_agent {
            req.headers_mut().set(UserAgent::new(Cow::Owned(user_agent.clone())));
        }




        // send request
        Box::new(
        configuration.client.request(req)
            .map_err(|e| Error::from(e))
            .and_then(|resp| {
                let status = resp.status();
                resp.body().concat2()
                    .and_then(move |body| Ok((status, body)))
                    .map_err(|e| Error::from(e))
            })
            .and_then(|(status, body)| {
                if status.is_success() {
                    Ok(body)
                } else {
                    Err(Error::from((status, &*body)))
                }
            })
            .and_then(|body| {
                let parsed: Result<::models::GetShippingLabelListResponse, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            })
        )
    }

    fn submit_shipping_label_request(&self, body: ::models::SubmitShippingLabelsRequest) -> Box<Future<Item = ::models::SubmitShippingLabelsResponse, Error = Error<serde_json::Value>>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Post;

        let query_string = {
            let mut query = ::url::form_urlencoded::Serializer::new(String::new());
            query.finish()
        };
        let uri_str = format!("{}/vendor/directFulfillment/shipping/v1/shippingLabels?{}", configuration.base_path, query_string);

        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut uri: hyper::Uri = uri_str.parse().unwrap();

        let mut req = hyper::Request::new(method, uri);

        if let Some(ref user_agent) = configuration.user_agent {
            req.headers_mut().set(UserAgent::new(Cow::Owned(user_agent.clone())));
        }



        let serialized = serde_json::to_string(&body).unwrap();
        req.headers_mut().set(hyper::header::ContentType::json());
        req.headers_mut().set(hyper::header::ContentLength(serialized.len() as u64));
        req.set_body(serialized);

        // send request
        Box::new(
        configuration.client.request(req)
            .map_err(|e| Error::from(e))
            .and_then(|resp| {
                let status = resp.status();
                resp.body().concat2()
                    .and_then(move |body| Ok((status, body)))
                    .map_err(|e| Error::from(e))
            })
            .and_then(|(status, body)| {
                if status.is_success() {
                    Ok(body)
                } else {
                    Err(Error::from((status, &*body)))
                }
            })
            .and_then(|body| {
                let parsed: Result<::models::SubmitShippingLabelsResponse, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            })
        )
    }

}
