/* 
 * Selling Partner API for Direct Fulfillment Payments
 *
 * The Selling Partner API for Direct Fulfillment Payments provides programmatic access to a direct fulfillment vendor's invoice data.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// SubmitInvoiceRequest : The request schema for the submitInvoice operation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SubmitInvoiceRequest {
  #[serde(rename = "invoices")]
  invoices: Option<Vec<::models::InvoiceDetail>>
}

impl SubmitInvoiceRequest {
  /// The request schema for the submitInvoice operation.
  pub fn new() -> SubmitInvoiceRequest {
    SubmitInvoiceRequest {
      invoices: None
    }
  }

  pub fn set_invoices(&mut self, invoices: Vec<::models::InvoiceDetail>) {
    self.invoices = Some(invoices);
  }

  pub fn with_invoices(mut self, invoices: Vec<::models::InvoiceDetail>) -> SubmitInvoiceRequest {
    self.invoices = Some(invoices);
    self
  }

  pub fn invoices(&self) -> Option<&Vec<::models::InvoiceDetail>> {
    self.invoices.as_ref()
  }

  pub fn reset_invoices(&mut self) {
    self.invoices = None;
  }

}



