/* 
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ErrorList : A list of error responses returned when a request is unsuccessful.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ErrorList {
}

impl ErrorList {
  /// A list of error responses returned when a request is unsuccessful.
  pub fn new() -> ErrorList {
    ErrorList {
    }
  }

}



