/* 
 * Selling Partner API for Shipment Invoicing
 *
 * The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetShipmentDetailsResponse : The response schema for the getShipmentDetails operation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetShipmentDetailsResponse {
  /// The payload for the getShipmentDetails operation
  #[serde(rename = "payload")]
  payload: Option<::models::ShipmentDetail>,
  #[serde(rename = "errors")]
  errors: Option<::models::ErrorList>
}

impl GetShipmentDetailsResponse {
  /// The response schema for the getShipmentDetails operation.
  pub fn new() -> GetShipmentDetailsResponse {
    GetShipmentDetailsResponse {
      payload: None,
      errors: None
    }
  }

  pub fn set_payload(&mut self, payload: ::models::ShipmentDetail) {
    self.payload = Some(payload);
  }

  pub fn with_payload(mut self, payload: ::models::ShipmentDetail) -> GetShipmentDetailsResponse {
    self.payload = Some(payload);
    self
  }

  pub fn payload(&self) -> Option<&::models::ShipmentDetail> {
    self.payload.as_ref()
  }

  pub fn reset_payload(&mut self) {
    self.payload = None;
  }

  pub fn set_errors(&mut self, errors: ::models::ErrorList) {
    self.errors = Some(errors);
  }

  pub fn with_errors(mut self, errors: ::models::ErrorList) -> GetShipmentDetailsResponse {
    self.errors = Some(errors);
    self
  }

  pub fn errors(&self) -> Option<&::models::ErrorList> {
    self.errors.as_ref()
  }

  pub fn reset_errors(&mut self) {
    self.errors = None;
  }

}



