/* 
 * Selling Partner API for Shipment Invoicing
 *
 * The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ShipmentInvoiceStatusResponse : The shipment invoice status response.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ShipmentInvoiceStatusResponse {
  #[serde(rename = "Shipments")]
  shipments: Option<::models::ShipmentInvoiceStatusInfo>
}

impl ShipmentInvoiceStatusResponse {
  /// The shipment invoice status response.
  pub fn new() -> ShipmentInvoiceStatusResponse {
    ShipmentInvoiceStatusResponse {
      shipments: None
    }
  }

  pub fn set_shipments(&mut self, shipments: ::models::ShipmentInvoiceStatusInfo) {
    self.shipments = Some(shipments);
  }

  pub fn with_shipments(mut self, shipments: ::models::ShipmentInvoiceStatusInfo) -> ShipmentInvoiceStatusResponse {
    self.shipments = Some(shipments);
    self
  }

  pub fn shipments(&self) -> Option<&::models::ShipmentInvoiceStatusInfo> {
    self.shipments.as_ref()
  }

  pub fn reset_shipments(&mut self) {
    self.shipments = None;
  }

}



