/* 
 * Selling Partner API for Messaging
 *
 * With the Messaging API you can build applications that send messages to buyers. You can get a list of message types that are available for an order that you specify, then call an operation that sends a message to the buyer for that order. The Messaging API returns responses that are formed according to the <a href=https://tools.ietf.org/html/draft-kelly-json-hal-08>JSON Hypertext Application Language</a> (HAL) standard.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetAttributesResponse : The response schema for the GetAttributes operation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetAttributesResponse {
  /// The list of attributes related to the buyer.
  #[serde(rename = "buyer")]
  buyer: Option<Value>,
  #[serde(rename = "errors")]
  errors: Option<::models::ErrorList>
}

impl GetAttributesResponse {
  /// The response schema for the GetAttributes operation.
  pub fn new() -> GetAttributesResponse {
    GetAttributesResponse {
      buyer: None,
      errors: None
    }
  }

  pub fn set_buyer(&mut self, buyer: Value) {
    self.buyer = Some(buyer);
  }

  pub fn with_buyer(mut self, buyer: Value) -> GetAttributesResponse {
    self.buyer = Some(buyer);
    self
  }

  pub fn buyer(&self) -> Option<&Value> {
    self.buyer.as_ref()
  }

  pub fn reset_buyer(&mut self) {
    self.buyer = None;
  }

  pub fn set_errors(&mut self, errors: ::models::ErrorList) {
    self.errors = Some(errors);
  }

  pub fn with_errors(mut self, errors: ::models::ErrorList) -> GetAttributesResponse {
    self.errors = Some(errors);
    self
  }

  pub fn errors(&self) -> Option<&::models::ErrorList> {
    self.errors.as_ref()
  }

  pub fn reset_errors(&mut self) {
    self.errors = None;
  }

}



