mod attachment;
pub use self::attachment::Attachment;
mod create_amazon_motors_request;
pub use self::create_amazon_motors_request::CreateAmazonMotorsRequest;
mod create_amazon_motors_response;
pub use self::create_amazon_motors_response::CreateAmazonMotorsResponse;
mod create_confirm_customization_details_request;
pub use self::create_confirm_customization_details_request::CreateConfirmCustomizationDetailsRequest;
mod create_confirm_customization_details_response;
pub use self::create_confirm_customization_details_response::CreateConfirmCustomizationDetailsResponse;
mod create_confirm_delivery_details_request;
pub use self::create_confirm_delivery_details_request::CreateConfirmDeliveryDetailsRequest;
mod create_confirm_delivery_details_response;
pub use self::create_confirm_delivery_details_response::CreateConfirmDeliveryDetailsResponse;
mod create_confirm_order_details_request;
pub use self::create_confirm_order_details_request::CreateConfirmOrderDetailsRequest;
mod create_confirm_order_details_response;
pub use self::create_confirm_order_details_response::CreateConfirmOrderDetailsResponse;
mod create_confirm_service_details_request;
pub use self::create_confirm_service_details_request::CreateConfirmServiceDetailsRequest;
mod create_confirm_service_details_response;
pub use self::create_confirm_service_details_response::CreateConfirmServiceDetailsResponse;
mod create_digital_access_key_request;
pub use self::create_digital_access_key_request::CreateDigitalAccessKeyRequest;
mod create_digital_access_key_response;
pub use self::create_digital_access_key_response::CreateDigitalAccessKeyResponse;
mod create_legal_disclosure_request;
pub use self::create_legal_disclosure_request::CreateLegalDisclosureRequest;
mod create_legal_disclosure_response;
pub use self::create_legal_disclosure_response::CreateLegalDisclosureResponse;
mod create_negative_feedback_removal_response;
pub use self::create_negative_feedback_removal_response::CreateNegativeFeedbackRemovalResponse;
mod create_unexpected_problem_request;
pub use self::create_unexpected_problem_request::CreateUnexpectedProblemRequest;
mod create_unexpected_problem_response;
pub use self::create_unexpected_problem_response::CreateUnexpectedProblemResponse;
mod create_warranty_request;
pub use self::create_warranty_request::CreateWarrantyRequest;
mod create_warranty_response;
pub use self::create_warranty_response::CreateWarrantyResponse;
mod error;
pub use self::error::Error;
mod error_list;
pub use self::error_list::ErrorList;
mod get_attributes_response;
pub use self::get_attributes_response::GetAttributesResponse;
mod get_messaging_action_response;
pub use self::get_messaging_action_response::GetMessagingActionResponse;
mod get_messaging_actions_for_order_response;
pub use self::get_messaging_actions_for_order_response::GetMessagingActionsForOrderResponse;
mod get_schema_response;
pub use self::get_schema_response::GetSchemaResponse;
mod link_object;
pub use self::link_object::LinkObject;
mod messaging_action;
pub use self::messaging_action::MessagingAction;
mod schema;
pub use self::schema::Schema;

// TODO(farcaller): sort out files
pub struct File;
