/* 
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CountryCode : The two digit country code. In ISO 3166-1 alpha-2 format.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CountryCode {
}

impl CountryCode {
  /// The two digit country code. In ISO 3166-1 alpha-2 format.
  pub fn new() -> CountryCode {
    CountryCode {
    }
  }

}



