mod accepted_rate;
pub use self::accepted_rate::AcceptedRate;
mod account;
pub use self::account::Account;
mod account_id;
pub use self::account_id::AccountId;
mod address;
pub use self::address::Address;
mod cancel_shipment_response;
pub use self::cancel_shipment_response::CancelShipmentResponse;
mod city;
pub use self::city::City;
mod client_reference_id;
pub use self::client_reference_id::ClientReferenceId;
mod container;
pub use self::container::Container;
mod container_item;
pub use self::container_item::ContainerItem;
mod container_list;
pub use self::container_list::ContainerList;
mod container_reference_id;
pub use self::container_reference_id::ContainerReferenceId;
mod container_specification;
pub use self::container_specification::ContainerSpecification;
mod container_specification_list;
pub use self::container_specification_list::ContainerSpecificationList;
mod country_code;
pub use self::country_code::CountryCode;
mod create_shipment_request;
pub use self::create_shipment_request::CreateShipmentRequest;
mod create_shipment_response;
pub use self::create_shipment_response::CreateShipmentResponse;
mod create_shipment_result;
pub use self::create_shipment_result::CreateShipmentResult;
mod currency;
pub use self::currency::Currency;
mod dimensions;
pub use self::dimensions::Dimensions;
mod error;
pub use self::error::Error;
mod error_list;
pub use self::error_list::ErrorList;
mod event;
pub use self::event::Event;
mod event_code;
pub use self::event_code::EventCode;
mod event_list;
pub use self::event_list::EventList;
mod get_account_response;
pub use self::get_account_response::GetAccountResponse;
mod get_rates_request;
pub use self::get_rates_request::GetRatesRequest;
mod get_rates_response;
pub use self::get_rates_response::GetRatesResponse;
mod get_rates_result;
pub use self::get_rates_result::GetRatesResult;
mod get_shipment_response;
pub use self::get_shipment_response::GetShipmentResponse;
mod get_tracking_information_response;
pub use self::get_tracking_information_response::GetTrackingInformationResponse;
mod label;
pub use self::label::Label;
mod label_result;
pub use self::label_result::LabelResult;
mod label_result_list;
pub use self::label_result_list::LabelResultList;
mod label_specification;
pub use self::label_specification::LabelSpecification;
mod label_stream;
pub use self::label_stream::LabelStream;
mod location;
pub use self::location::Location;
mod party;
pub use self::party::Party;
mod postal_code;
pub use self::postal_code::PostalCode;
mod promised_delivery_date;
pub use self::promised_delivery_date::PromisedDeliveryDate;
mod purchase_labels_request;
pub use self::purchase_labels_request::PurchaseLabelsRequest;
mod purchase_labels_response;
pub use self::purchase_labels_response::PurchaseLabelsResponse;
mod purchase_labels_result;
pub use self::purchase_labels_result::PurchaseLabelsResult;
mod purchase_shipment_request;
pub use self::purchase_shipment_request::PurchaseShipmentRequest;
mod purchase_shipment_response;
pub use self::purchase_shipment_response::PurchaseShipmentResponse;
mod purchase_shipment_result;
pub use self::purchase_shipment_result::PurchaseShipmentResult;
mod rate;
pub use self::rate::Rate;
mod rate_id;
pub use self::rate_id::RateId;
mod rate_list;
pub use self::rate_list::RateList;
mod retrieve_shipping_label_request;
pub use self::retrieve_shipping_label_request::RetrieveShippingLabelRequest;
mod retrieve_shipping_label_response;
pub use self::retrieve_shipping_label_response::RetrieveShippingLabelResponse;
mod retrieve_shipping_label_result;
pub use self::retrieve_shipping_label_result::RetrieveShippingLabelResult;
mod service_rate;
pub use self::service_rate::ServiceRate;
mod service_rate_list;
pub use self::service_rate_list::ServiceRateList;
mod service_type;
pub use self::service_type::ServiceType;
mod service_type_list;
pub use self::service_type_list::ServiceTypeList;
mod shipment;
pub use self::shipment::Shipment;
mod shipment_id;
pub use self::shipment_id::ShipmentId;
mod shipping_promise_set;
pub use self::shipping_promise_set::ShippingPromiseSet;
mod state_or_region;
pub use self::state_or_region::StateOrRegion;
mod time_range;
pub use self::time_range::TimeRange;
mod tracking_id;
pub use self::tracking_id::TrackingId;
mod tracking_information;
pub use self::tracking_information::TrackingInformation;
mod tracking_summary;
pub use self::tracking_summary::TrackingSummary;
mod weight;
pub use self::weight::Weight;

// TODO(farcaller): sort out files
pub struct File;
