/* 
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Party : The account related with the shipment.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Party {
  #[serde(rename = "accountId")]
  account_id: Option<::models::AccountId>
}

impl Party {
  /// The account related with the shipment.
  pub fn new() -> Party {
    Party {
      account_id: None
    }
  }

  pub fn set_account_id(&mut self, account_id: ::models::AccountId) {
    self.account_id = Some(account_id);
  }

  pub fn with_account_id(mut self, account_id: ::models::AccountId) -> Party {
    self.account_id = Some(account_id);
    self
  }

  pub fn account_id(&self) -> Option<&::models::AccountId> {
    self.account_id.as_ref()
  }

  pub fn reset_account_id(&mut self) {
    self.account_id = None;
  }

}



