/* 
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// PurchaseLabelsRequest : The request schema for the purchaseLabels operation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PurchaseLabelsRequest {
  #[serde(rename = "rateId")]
  rate_id: ::models::RateId,
  #[serde(rename = "labelSpecification")]
  label_specification: ::models::LabelSpecification
}

impl PurchaseLabelsRequest {
  /// The request schema for the purchaseLabels operation.
  pub fn new(rate_id: ::models::RateId, label_specification: ::models::LabelSpecification) -> PurchaseLabelsRequest {
    PurchaseLabelsRequest {
      rate_id: rate_id,
      label_specification: label_specification
    }
  }

  pub fn set_rate_id(&mut self, rate_id: ::models::RateId) {
    self.rate_id = rate_id;
  }

  pub fn with_rate_id(mut self, rate_id: ::models::RateId) -> PurchaseLabelsRequest {
    self.rate_id = rate_id;
    self
  }

  pub fn rate_id(&self) -> &::models::RateId {
    &self.rate_id
  }


  pub fn set_label_specification(&mut self, label_specification: ::models::LabelSpecification) {
    self.label_specification = label_specification;
  }

  pub fn with_label_specification(mut self, label_specification: ::models::LabelSpecification) -> PurchaseLabelsRequest {
    self.label_specification = label_specification;
    self
  }

  pub fn label_specification(&self) -> &::models::LabelSpecification {
    &self.label_specification
  }


}



