/* 
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ServiceType : The type of shipping service that will be used for the service offering.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ServiceType {
}

impl ServiceType {
  /// The type of shipping service that will be used for the service offering.
  pub fn new() -> ServiceType {
    ServiceType {
    }
  }

}

// TODO enum 
// List of ServiceType
//const (
//  
//  
//  
//)


