/* 
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AvailableDeliveryExperienceOption : The available delivery confirmation options, and the fee charged, if any.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AvailableDeliveryExperienceOption {
  #[serde(rename = "DeliveryExperienceOption")]
  delivery_experience_option: ::models::DeliveryExperienceOption,
  #[serde(rename = "Charge")]
  charge: ::models::CurrencyAmount
}

impl AvailableDeliveryExperienceOption {
  /// The available delivery confirmation options, and the fee charged, if any.
  pub fn new(delivery_experience_option: ::models::DeliveryExperienceOption, charge: ::models::CurrencyAmount) -> AvailableDeliveryExperienceOption {
    AvailableDeliveryExperienceOption {
      delivery_experience_option: delivery_experience_option,
      charge: charge
    }
  }

  pub fn set_delivery_experience_option(&mut self, delivery_experience_option: ::models::DeliveryExperienceOption) {
    self.delivery_experience_option = delivery_experience_option;
  }

  pub fn with_delivery_experience_option(mut self, delivery_experience_option: ::models::DeliveryExperienceOption) -> AvailableDeliveryExperienceOption {
    self.delivery_experience_option = delivery_experience_option;
    self
  }

  pub fn delivery_experience_option(&self) -> &::models::DeliveryExperienceOption {
    &self.delivery_experience_option
  }


  pub fn set_charge(&mut self, charge: ::models::CurrencyAmount) {
    self.charge = charge;
  }

  pub fn with_charge(mut self, charge: ::models::CurrencyAmount) -> AvailableDeliveryExperienceOption {
    self.charge = charge;
    self
  }

  pub fn charge(&self) -> &::models::CurrencyAmount {
    &self.charge
  }


}



