/* 
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CountryCode : The country code. A two-character country code, in ISO 3166-1 alpha-2 format.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CountryCode {
}

impl CountryCode {
  /// The country code. A two-character country code, in ISO 3166-1 alpha-2 format.
  pub fn new() -> CountryCode {
    CountryCode {
    }
  }

}



