/* 
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CurrencyAmount : Currency type and amount.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CurrencyAmount {
  /// Three-digit currency code in ISO 4217 format.
  #[serde(rename = "CurrencyCode")]
  currency_code: String,
  /// The currency amount.
  #[serde(rename = "Amount")]
  amount: f64
}

impl CurrencyAmount {
  /// Currency type and amount.
  pub fn new(currency_code: String, amount: f64) -> CurrencyAmount {
    CurrencyAmount {
      currency_code: currency_code,
      amount: amount
    }
  }

  pub fn set_currency_code(&mut self, currency_code: String) {
    self.currency_code = currency_code;
  }

  pub fn with_currency_code(mut self, currency_code: String) -> CurrencyAmount {
    self.currency_code = currency_code;
    self
  }

  pub fn currency_code(&self) -> &String {
    &self.currency_code
  }


  pub fn set_amount(&mut self, amount: f64) {
    self.amount = amount;
  }

  pub fn with_amount(mut self, amount: f64) -> CurrencyAmount {
    self.amount = amount;
    self
  }

  pub fn amount(&self) -> &f64 {
    &self.amount
  }


}



