/* 
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ItemLevelFields {
  /// The Amazon Standard Identification Number (ASIN) of the item.
  #[serde(rename = "Asin")]
  asin: String,
  #[serde(rename = "AdditionalInputs")]
  additional_inputs: ::models::AdditionalInputsList
}

impl ItemLevelFields {
  pub fn new(asin: String, additional_inputs: ::models::AdditionalInputsList) -> ItemLevelFields {
    ItemLevelFields {
      asin: asin,
      additional_inputs: additional_inputs
    }
  }

  pub fn set_asin(&mut self, asin: String) {
    self.asin = asin;
  }

  pub fn with_asin(mut self, asin: String) -> ItemLevelFields {
    self.asin = asin;
    self
  }

  pub fn asin(&self) -> &String {
    &self.asin
  }


  pub fn set_additional_inputs(&mut self, additional_inputs: ::models::AdditionalInputsList) {
    self.additional_inputs = additional_inputs;
  }

  pub fn with_additional_inputs(mut self, additional_inputs: ::models::AdditionalInputsList) -> ItemLevelFields {
    self.additional_inputs = additional_inputs;
    self
  }

  pub fn additional_inputs(&self) -> &::models::AdditionalInputsList {
    &self.additional_inputs
  }


}



