/* 
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// UnitOfLength : The unit of length.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UnitOfLength {
}

impl UnitOfLength {
  /// The unit of length.
  pub fn new() -> UnitOfLength {
    UnitOfLength {
    }
  }

}

// TODO enum 
// List of UnitOfLength
//const (
//  
//  
//  
//)


