/* 
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Weight : The weight.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Weight {
  #[serde(rename = "Value")]
  value: ::models::WeightValue,
  #[serde(rename = "Unit")]
  unit: ::models::UnitOfWeight
}

impl Weight {
  /// The weight.
  pub fn new(value: ::models::WeightValue, unit: ::models::UnitOfWeight) -> Weight {
    Weight {
      value: value,
      unit: unit
    }
  }

  pub fn set_value(&mut self, value: ::models::WeightValue) {
    self.value = value;
  }

  pub fn with_value(mut self, value: ::models::WeightValue) -> Weight {
    self.value = value;
    self
  }

  pub fn value(&self) -> &::models::WeightValue {
    &self.value
  }


  pub fn set_unit(&mut self, unit: ::models::UnitOfWeight) {
    self.unit = unit;
  }

  pub fn with_unit(mut self, unit: ::models::UnitOfWeight) -> Weight {
    self.unit = unit;
    self
  }

  pub fn unit(&self) -> &::models::UnitOfWeight {
    &self.unit
  }


}



