=begin
#Selling Partner API for Pricing

#The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.21

=end

require 'date'

module SwaggerClient
  class OfferDetail
    # The seller identifier for the offer.
    attr_accessor :seller_id

    # When true, this is the seller's offer.
    attr_accessor :my_offer

    # Indicates the type of customer that the offer is valid for.
    attr_accessor :offer_type

    # The subcondition of the item. Subcondition values: New, Mint, Very Good, Good, Acceptable, Poor, Club, OEM, Warranty, Refurbished Warranty, Refurbished, Open Box, or Other.
    attr_accessor :sub_condition

    # Information about the seller's feedback, including the percentage of positive feedback, and the total number of ratings received.
    attr_accessor :seller_feedback_rating

    # The maximum time within which the item will likely be shipped once an order has been placed.
    attr_accessor :shipping_time

    # The price of the item.
    attr_accessor :listing_price

    attr_accessor :quantity_discount_prices

    # The number of Amazon Points offered with the purchase of an item.
    attr_accessor :points

    # The shipping cost.
    attr_accessor :shipping

    # The state and country from where the item is shipped.
    attr_accessor :ships_from

    # When true, the offer is fulfilled by Amazon.
    attr_accessor :is_fulfilled_by_amazon

    # When true, the offer is currently in the Buy Box. There can be up to two Buy Box winners at any time per ASIN, one that is eligible for Prime and one that is not eligible for Prime.
    attr_accessor :is_buy_box_winner

    # When true, the seller of the item is eligible to win the Buy Box.
    attr_accessor :is_featured_merchant

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'seller_id' => :'sellerId',
        :'my_offer' => :'MyOffer',
        :'offer_type' => :'offerType',
        :'sub_condition' => :'SubCondition',
        :'seller_feedback_rating' => :'SellerFeedbackRating',
        :'shipping_time' => :'ShippingTime',
        :'listing_price' => :'ListingPrice',
        :'quantity_discount_prices' => :'quantityDiscountPrices',
        :'points' => :'Points',
        :'shipping' => :'Shipping',
        :'ships_from' => :'ShipsFrom',
        :'is_fulfilled_by_amazon' => :'IsFulfilledByAmazon',
        :'is_buy_box_winner' => :'IsBuyBoxWinner',
        :'is_featured_merchant' => :'IsFeaturedMerchant'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'seller_id' => :'String',
        :'my_offer' => :'BOOLEAN',
        :'offer_type' => :'OfferCustomerType',
        :'sub_condition' => :'String',
        :'seller_feedback_rating' => :'SellerFeedbackType',
        :'shipping_time' => :'DetailedShippingTimeType',
        :'listing_price' => :'MoneyType',
        :'quantity_discount_prices' => :'Array<QuantityDiscountPriceType>',
        :'points' => :'Points',
        :'shipping' => :'MoneyType',
        :'ships_from' => :'ShipsFromType',
        :'is_fulfilled_by_amazon' => :'BOOLEAN',
        :'is_buy_box_winner' => :'BOOLEAN',
        :'is_featured_merchant' => :'BOOLEAN'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'sellerId')
        self.seller_id = attributes[:'sellerId']
      end

      if attributes.has_key?(:'MyOffer')
        self.my_offer = attributes[:'MyOffer']
      end

      if attributes.has_key?(:'offerType')
        self.offer_type = attributes[:'offerType']
      end

      if attributes.has_key?(:'SubCondition')
        self.sub_condition = attributes[:'SubCondition']
      end

      if attributes.has_key?(:'SellerFeedbackRating')
        self.seller_feedback_rating = attributes[:'SellerFeedbackRating']
      end

      if attributes.has_key?(:'ShippingTime')
        self.shipping_time = attributes[:'ShippingTime']
      end

      if attributes.has_key?(:'ListingPrice')
        self.listing_price = attributes[:'ListingPrice']
      end

      if attributes.has_key?(:'quantityDiscountPrices')
        if (value = attributes[:'quantityDiscountPrices']).is_a?(Array)
          self.quantity_discount_prices = value
        end
      end

      if attributes.has_key?(:'Points')
        self.points = attributes[:'Points']
      end

      if attributes.has_key?(:'Shipping')
        self.shipping = attributes[:'Shipping']
      end

      if attributes.has_key?(:'ShipsFrom')
        self.ships_from = attributes[:'ShipsFrom']
      end

      if attributes.has_key?(:'IsFulfilledByAmazon')
        self.is_fulfilled_by_amazon = attributes[:'IsFulfilledByAmazon']
      end

      if attributes.has_key?(:'IsBuyBoxWinner')
        self.is_buy_box_winner = attributes[:'IsBuyBoxWinner']
      end

      if attributes.has_key?(:'IsFeaturedMerchant')
        self.is_featured_merchant = attributes[:'IsFeaturedMerchant']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @sub_condition.nil?
        invalid_properties.push('invalid value for "sub_condition", sub_condition cannot be nil.')
      end

      if @shipping_time.nil?
        invalid_properties.push('invalid value for "shipping_time", shipping_time cannot be nil.')
      end

      if @listing_price.nil?
        invalid_properties.push('invalid value for "listing_price", listing_price cannot be nil.')
      end

      if @shipping.nil?
        invalid_properties.push('invalid value for "shipping", shipping cannot be nil.')
      end

      if @is_fulfilled_by_amazon.nil?
        invalid_properties.push('invalid value for "is_fulfilled_by_amazon", is_fulfilled_by_amazon cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @sub_condition.nil?
      return false if @shipping_time.nil?
      return false if @listing_price.nil?
      return false if @shipping.nil?
      return false if @is_fulfilled_by_amazon.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          seller_id == o.seller_id &&
          my_offer == o.my_offer &&
          offer_type == o.offer_type &&
          sub_condition == o.sub_condition &&
          seller_feedback_rating == o.seller_feedback_rating &&
          shipping_time == o.shipping_time &&
          listing_price == o.listing_price &&
          quantity_discount_prices == o.quantity_discount_prices &&
          points == o.points &&
          shipping == o.shipping &&
          ships_from == o.ships_from &&
          is_fulfilled_by_amazon == o.is_fulfilled_by_amazon &&
          is_buy_box_winner == o.is_buy_box_winner &&
          is_featured_merchant == o.is_featured_merchant
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [seller_id, my_offer, offer_type, sub_condition, seller_feedback_rating, shipping_time, listing_price, quantity_discount_prices, points, shipping, ships_from, is_fulfilled_by_amazon, is_buy_box_winner, is_featured_merchant].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
