mod create_destination_request;
pub use self::create_destination_request::CreateDestinationRequest;
mod create_destination_response;
pub use self::create_destination_response::CreateDestinationResponse;
mod create_subscription_request;
pub use self::create_subscription_request::CreateSubscriptionRequest;
mod create_subscription_response;
pub use self::create_subscription_response::CreateSubscriptionResponse;
mod delete_destination_response;
pub use self::delete_destination_response::DeleteDestinationResponse;
mod delete_subscription_by_id_response;
pub use self::delete_subscription_by_id_response::DeleteSubscriptionByIdResponse;
mod destination;
pub use self::destination::Destination;
mod destination_list;
pub use self::destination_list::DestinationList;
mod destination_resource;
pub use self::destination_resource::DestinationResource;
mod destination_resource_specification;
pub use self::destination_resource_specification::DestinationResourceSpecification;
mod error;
pub use self::error::Error;
mod error_list;
pub use self::error_list::ErrorList;
mod event_bridge_resource;
pub use self::event_bridge_resource::EventBridgeResource;
mod event_bridge_resource_specification;
pub use self::event_bridge_resource_specification::EventBridgeResourceSpecification;
mod get_destination_response;
pub use self::get_destination_response::GetDestinationResponse;
mod get_destinations_response;
pub use self::get_destinations_response::GetDestinationsResponse;
mod get_subscription_by_id_response;
pub use self::get_subscription_by_id_response::GetSubscriptionByIdResponse;
mod get_subscription_response;
pub use self::get_subscription_response::GetSubscriptionResponse;
mod sqs_resource;
pub use self::sqs_resource::SqsResource;
mod subscription;
pub use self::subscription::Subscription;

// TODO(farcaller): sort out files
pub struct File;
