/* 
 * Selling Partner API for Direct Fulfillment Orders
 *
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetOrderResponse : The response schema for the getOrder operation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetOrderResponse {
  /// The payload for the getOrder operation.
  #[serde(rename = "payload")]
  payload: Option<::models::Order>,
  #[serde(rename = "errors")]
  errors: Option<::models::ErrorList>
}

impl GetOrderResponse {
  /// The response schema for the getOrder operation.
  pub fn new() -> GetOrderResponse {
    GetOrderResponse {
      payload: None,
      errors: None
    }
  }

  pub fn set_payload(&mut self, payload: ::models::Order) {
    self.payload = Some(payload);
  }

  pub fn with_payload(mut self, payload: ::models::Order) -> GetOrderResponse {
    self.payload = Some(payload);
    self
  }

  pub fn payload(&self) -> Option<&::models::Order> {
    self.payload.as_ref()
  }

  pub fn reset_payload(&mut self) {
    self.payload = None;
  }

  pub fn set_errors(&mut self, errors: ::models::ErrorList) {
    self.errors = Some(errors);
  }

  pub fn with_errors(mut self, errors: ::models::ErrorList) -> GetOrderResponse {
    self.errors = Some(errors);
    self
  }

  pub fn errors(&self) -> Option<&::models::ErrorList> {
    self.errors.as_ref()
  }

  pub fn reset_errors(&mut self) {
    self.errors = None;
  }

}



