/* 
 * Selling Partner API for Direct Fulfillment Orders
 *
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetOrdersResponse : The response schema for the getOrders operation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetOrdersResponse {
  /// A list of purchase orders.
  #[serde(rename = "payload")]
  payload: Option<::models::OrderList>,
  #[serde(rename = "errors")]
  errors: Option<::models::ErrorList>
}

impl GetOrdersResponse {
  /// The response schema for the getOrders operation.
  pub fn new() -> GetOrdersResponse {
    GetOrdersResponse {
      payload: None,
      errors: None
    }
  }

  pub fn set_payload(&mut self, payload: ::models::OrderList) {
    self.payload = Some(payload);
  }

  pub fn with_payload(mut self, payload: ::models::OrderList) -> GetOrdersResponse {
    self.payload = Some(payload);
    self
  }

  pub fn payload(&self) -> Option<&::models::OrderList> {
    self.payload.as_ref()
  }

  pub fn reset_payload(&mut self) {
    self.payload = None;
  }

  pub fn set_errors(&mut self, errors: ::models::ErrorList) {
    self.errors = Some(errors);
  }

  pub fn with_errors(mut self, errors: ::models::ErrorList) -> GetOrdersResponse {
    self.errors = Some(errors);
    self
  }

  pub fn errors(&self) -> Option<&::models::ErrorList> {
    self.errors.as_ref()
  }

  pub fn reset_errors(&mut self) {
    self.errors = None;
  }

}



