/* 
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GetServiceJobByServiceJobIdResponse : The response schema for the GetServiceJobByServiceJobId operation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GetServiceJobByServiceJobIdResponse {
  /// The payload for the GetServiceJobByServiceJobId operation.
  #[serde(rename = "payload")]
  payload: Option<::models::ServiceJob>,
  /// An unexpected condition occurred during the GetServiceJobByServiceJobId operation.
  #[serde(rename = "errors")]
  errors: Option<::models::ErrorList>
}

impl GetServiceJobByServiceJobIdResponse {
  /// The response schema for the GetServiceJobByServiceJobId operation.
  pub fn new() -> GetServiceJobByServiceJobIdResponse {
    GetServiceJobByServiceJobIdResponse {
      payload: None,
      errors: None
    }
  }

  pub fn set_payload(&mut self, payload: ::models::ServiceJob) {
    self.payload = Some(payload);
  }

  pub fn with_payload(mut self, payload: ::models::ServiceJob) -> GetServiceJobByServiceJobIdResponse {
    self.payload = Some(payload);
    self
  }

  pub fn payload(&self) -> Option<&::models::ServiceJob> {
    self.payload.as_ref()
  }

  pub fn reset_payload(&mut self) {
    self.payload = None;
  }

  pub fn set_errors(&mut self, errors: ::models::ErrorList) {
    self.errors = Some(errors);
  }

  pub fn with_errors(mut self, errors: ::models::ErrorList) -> GetServiceJobByServiceJobIdResponse {
    self.errors = Some(errors);
    self
  }

  pub fn errors(&self) -> Option<&::models::ErrorList> {
    self.errors.as_ref()
  }

  pub fn reset_errors(&mut self) {
    self.errors = None;
  }

}



