/* 
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ServiceJobId : Amazon identifier for the service job.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ServiceJobId {
}

impl ServiceJobId {
  /// Amazon identifier for the service job.
  pub fn new() -> ServiceJobId {
    ServiceJobId {
    }
  }

}



