/* 
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ServiceJobProvider : Information about the service job provider.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ServiceJobProvider {
  /// The identifier of the service job provider.
  #[serde(rename = "serviceJobProviderId")]
  service_job_provider_id: Option<String>
}

impl ServiceJobProvider {
  /// Information about the service job provider.
  pub fn new() -> ServiceJobProvider {
    ServiceJobProvider {
      service_job_provider_id: None
    }
  }

  pub fn set_service_job_provider_id(&mut self, service_job_provider_id: String) {
    self.service_job_provider_id = Some(service_job_provider_id);
  }

  pub fn with_service_job_provider_id(mut self, service_job_provider_id: String) -> ServiceJobProvider {
    self.service_job_provider_id = Some(service_job_provider_id);
    self
  }

  pub fn service_job_provider_id(&self) -> Option<&String> {
    self.service_job_provider_id.as_ref()
  }

  pub fn reset_service_job_provider_id(&mut self) {
    self.service_job_provider_id = None;
  }

}



