/* 
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SubmitShippingLabelsRequest {
  #[serde(rename = "shippingLabelRequests")]
  shipping_label_requests: Option<Vec<::models::ShippingLabelRequest>>
}

impl SubmitShippingLabelsRequest {
  pub fn new() -> SubmitShippingLabelsRequest {
    SubmitShippingLabelsRequest {
      shipping_label_requests: None
    }
  }

  pub fn set_shipping_label_requests(&mut self, shipping_label_requests: Vec<::models::ShippingLabelRequest>) {
    self.shipping_label_requests = Some(shipping_label_requests);
  }

  pub fn with_shipping_label_requests(mut self, shipping_label_requests: Vec<::models::ShippingLabelRequest>) -> SubmitShippingLabelsRequest {
    self.shipping_label_requests = Some(shipping_label_requests);
    self
  }

  pub fn shipping_label_requests(&self) -> Option<&Vec<::models::ShippingLabelRequest>> {
    self.shipping_label_requests.as_ref()
  }

  pub fn reset_shipping_label_requests(&mut self) {
    self.shipping_label_requests = None;
  }

}



