/* 
 * Selling Partner API for Sales
 *
 * The Selling Partner API for Sales provides APIs related to sales performance.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;
use std::borrow::Cow;
use std::collections::HashMap;

use hyper;
use serde_json;
use futures;
use futures::{Future, Stream};

use hyper::header::UserAgent;

use super::{Error, configuration};

pub struct SalesApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> SalesApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> SalesApiClient<C> {
        SalesApiClient {
            configuration: configuration,
        }
    }
}

pub trait SalesApi {
    fn get_order_metrics(&self, marketplace_ids: Vec<String>, interval: &str, granularity: &str, granularity_time_zone: &str, buyer_type: &str, fulfillment_network: &str, first_day_of_week: &str, asin: &str, sku: &str) -> Box<Future<Item = ::models::GetOrderMetricsResponse, Error = Error<serde_json::Value>>>;
}


impl<C: hyper::client::Connect>SalesApi for SalesApiClient<C> {
    fn get_order_metrics(&self, marketplace_ids: Vec<String>, interval: &str, granularity: &str, granularity_time_zone: &str, buyer_type: &str, fulfillment_network: &str, first_day_of_week: &str, asin: &str, sku: &str) -> Box<Future<Item = ::models::GetOrderMetricsResponse, Error = Error<serde_json::Value>>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query_string = {
            let mut query = ::url::form_urlencoded::Serializer::new(String::new());
            query.append_pair("marketplaceIds", &marketplace_ids.join(",").to_string());
            query.append_pair("interval", &interval.to_string());
            query.append_pair("granularityTimeZone", &granularity_time_zone.to_string());
            query.append_pair("granularity", &granularity.to_string());
            query.append_pair("buyerType", &buyer_type.to_string());
            query.append_pair("fulfillmentNetwork", &fulfillment_network.to_string());
            query.append_pair("firstDayOfWeek", &first_day_of_week.to_string());
            query.append_pair("asin", &asin.to_string());
            query.append_pair("sku", &sku.to_string());
            query.finish()
        };
        let uri_str = format!("{}/sales/v1/orderMetrics?{}", configuration.base_path, query_string);

        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut uri: hyper::Uri = uri_str.parse().unwrap();

        let mut req = hyper::Request::new(method, uri);

        if let Some(ref user_agent) = configuration.user_agent {
            req.headers_mut().set(UserAgent::new(Cow::Owned(user_agent.clone())));
        }




        // send request
        Box::new(
        configuration.client.request(req)
            .map_err(|e| Error::from(e))
            .and_then(|resp| {
                let status = resp.status();
                resp.body().concat2()
                    .and_then(move |body| Ok((status, body)))
                    .map_err(|e| Error::from(e))
            })
            .and_then(|(status, body)| {
                if status.is_success() {
                    Ok(body)
                } else {
                    Err(Error::from((status, &*body)))
                }
            })
            .and_then(|body| {
                let parsed: Result<::models::GetOrderMetricsResponse, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            })
        )
    }

}
