/* 
 * Selling Partner API for Direct Fulfillment Inventory Updates
 *
 * The Selling Partner API for Direct Fulfillment Inventory Updates provides programmatic access to a direct fulfillment vendor's inventory updates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ItemQuantity : Details of item quantity.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ItemQuantity {
  /// Quantity of units available for a specific item.
  #[serde(rename = "amount")]
  amount: Option<i32>,
  /// Unit of measure for the available quantity.
  #[serde(rename = "unitOfMeasure")]
  unit_of_measure: String
}

impl ItemQuantity {
  /// Details of item quantity.
  pub fn new(unit_of_measure: String) -> ItemQuantity {
    ItemQuantity {
      amount: None,
      unit_of_measure: unit_of_measure
    }
  }

  pub fn set_amount(&mut self, amount: i32) {
    self.amount = Some(amount);
  }

  pub fn with_amount(mut self, amount: i32) -> ItemQuantity {
    self.amount = Some(amount);
    self
  }

  pub fn amount(&self) -> Option<&i32> {
    self.amount.as_ref()
  }

  pub fn reset_amount(&mut self) {
    self.amount = None;
  }

  pub fn set_unit_of_measure(&mut self, unit_of_measure: String) {
    self.unit_of_measure = unit_of_measure;
  }

  pub fn with_unit_of_measure(mut self, unit_of_measure: String) -> ItemQuantity {
    self.unit_of_measure = unit_of_measure;
    self
  }

  pub fn unit_of_measure(&self) -> &String {
    &self.unit_of_measure
  }


}



