/* 
 * Selling Partner API for Product Fees
 *
 * The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FeeDetailList : A list of other fees that contribute to a given fee.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FeeDetailList {
}

impl FeeDetailList {
  /// A list of other fees that contribute to a given fee.
  pub fn new() -> FeeDetailList {
    FeeDetailList {
    }
  }

}



