/* 
 * Selling Partner API for Uploads
 *
 * The Uploads API lets you upload files that you can programmatically access using other Selling Partner APIs, such as the A+ Content API and the Messaging API.
 *
 * OpenAPI spec version: 2020-11-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CreateUploadDestinationResponse : The response schema for the createUploadDestination operation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateUploadDestinationResponse {
  #[serde(rename = "payload")]
  payload: Option<::models::UploadDestination>,
  #[serde(rename = "errors")]
  errors: Option<::models::ErrorList>
}

impl CreateUploadDestinationResponse {
  /// The response schema for the createUploadDestination operation.
  pub fn new() -> CreateUploadDestinationResponse {
    CreateUploadDestinationResponse {
      payload: None,
      errors: None
    }
  }

  pub fn set_payload(&mut self, payload: ::models::UploadDestination) {
    self.payload = Some(payload);
  }

  pub fn with_payload(mut self, payload: ::models::UploadDestination) -> CreateUploadDestinationResponse {
    self.payload = Some(payload);
    self
  }

  pub fn payload(&self) -> Option<&::models::UploadDestination> {
    self.payload.as_ref()
  }

  pub fn reset_payload(&mut self) {
    self.payload = None;
  }

  pub fn set_errors(&mut self, errors: ::models::ErrorList) {
    self.errors = Some(errors);
  }

  pub fn with_errors(mut self, errors: ::models::ErrorList) -> CreateUploadDestinationResponse {
    self.errors = Some(errors);
    self
  }

  pub fn errors(&self) -> Option<&::models::ErrorList> {
    self.errors.as_ref()
  }

  pub fn reset_errors(&mut self) {
    self.errors = None;
  }

}



