/* 
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AmazonPrepFeesDetailsList : A list of preparation instructions and fees for Amazon to prep goods for shipment.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AmazonPrepFeesDetailsList {
}

impl AmazonPrepFeesDetailsList {
  /// A list of preparation instructions and fees for Amazon to prep goods for shipment.
  pub fn new() -> AmazonPrepFeesDetailsList {
    AmazonPrepFeesDetailsList {
    }
  }

}



