/* 
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// BoxContentsSource : Where the seller provided box contents information for a shipment.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BoxContentsSource {
}

impl BoxContentsSource {
  /// Where the seller provided box contents information for a shipment.
  pub fn new() -> BoxContentsSource {
    BoxContentsSource {
    }
  }

}

// TODO enum 
// List of BoxContentsSource
//const (
//  
//  
//  
//)


