/* 
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// EstimateTransportResponse : The response schema for the estimateTransport operation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct EstimateTransportResponse {
  /// The payload for the estimateTransport operation.
  #[serde(rename = "payload")]
  payload: Option<::models::CommonTransportResult>,
  #[serde(rename = "errors")]
  errors: Option<::models::ErrorList>
}

impl EstimateTransportResponse {
  /// The response schema for the estimateTransport operation.
  pub fn new() -> EstimateTransportResponse {
    EstimateTransportResponse {
      payload: None,
      errors: None
    }
  }

  pub fn set_payload(&mut self, payload: ::models::CommonTransportResult) {
    self.payload = Some(payload);
  }

  pub fn with_payload(mut self, payload: ::models::CommonTransportResult) -> EstimateTransportResponse {
    self.payload = Some(payload);
    self
  }

  pub fn payload(&self) -> Option<&::models::CommonTransportResult> {
    self.payload.as_ref()
  }

  pub fn reset_payload(&mut self) {
    self.payload = None;
  }

  pub fn set_errors(&mut self, errors: ::models::ErrorList) {
    self.errors = Some(errors);
  }

  pub fn with_errors(mut self, errors: ::models::ErrorList) -> EstimateTransportResponse {
    self.errors = Some(errors);
    self
  }

  pub fn errors(&self) -> Option<&::models::ErrorList> {
    self.errors.as_ref()
  }

  pub fn reset_errors(&mut self) {
    self.errors = None;
  }

}



