/* 
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GuidanceReasonList : A list of inbound guidance reason information.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GuidanceReasonList {
}

impl GuidanceReasonList {
  /// A list of inbound guidance reason information.
  pub fn new() -> GuidanceReasonList {
    GuidanceReasonList {
    }
  }

}



