/* 
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// InboundShipmentPlanList : A list of inbound shipment plan information

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InboundShipmentPlanList {
}

impl InboundShipmentPlanList {
  /// A list of inbound shipment plan information
  pub fn new() -> InboundShipmentPlanList {
    InboundShipmentPlanList {
    }
  }

}



