/* 
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// NonPartneredSmallParcelDataOutput : Information returned by Amazon about a Small Parcel shipment by a carrier that has not partnered with Amazon.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NonPartneredSmallParcelDataOutput {
  #[serde(rename = "PackageList")]
  package_list: ::models::NonPartneredSmallParcelPackageOutputList
}

impl NonPartneredSmallParcelDataOutput {
  /// Information returned by Amazon about a Small Parcel shipment by a carrier that has not partnered with Amazon.
  pub fn new(package_list: ::models::NonPartneredSmallParcelPackageOutputList) -> NonPartneredSmallParcelDataOutput {
    NonPartneredSmallParcelDataOutput {
      package_list: package_list
    }
  }

  pub fn set_package_list(&mut self, package_list: ::models::NonPartneredSmallParcelPackageOutputList) {
    self.package_list = package_list;
  }

  pub fn with_package_list(mut self, package_list: ::models::NonPartneredSmallParcelPackageOutputList) -> NonPartneredSmallParcelDataOutput {
    self.package_list = package_list;
    self
  }

  pub fn package_list(&self) -> &::models::NonPartneredSmallParcelPackageOutputList {
    &self.package_list
  }


}



