/* 
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// NonPartneredSmallParcelPackageOutputList : A list of packages, including carrier, tracking number, and status information for each package.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NonPartneredSmallParcelPackageOutputList {
}

impl NonPartneredSmallParcelPackageOutputList {
  /// A list of packages, including carrier, tracking number, and status information for each package.
  pub fn new() -> NonPartneredSmallParcelPackageOutputList {
    NonPartneredSmallParcelPackageOutputList {
    }
  }

}



