/* 
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// PrepDetails : Preparation instructions and who is responsible for the preparation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PrepDetails {
  #[serde(rename = "PrepInstruction")]
  prep_instruction: ::models::PrepInstruction,
  #[serde(rename = "PrepOwner")]
  prep_owner: ::models::PrepOwner
}

impl PrepDetails {
  /// Preparation instructions and who is responsible for the preparation.
  pub fn new(prep_instruction: ::models::PrepInstruction, prep_owner: ::models::PrepOwner) -> PrepDetails {
    PrepDetails {
      prep_instruction: prep_instruction,
      prep_owner: prep_owner
    }
  }

  pub fn set_prep_instruction(&mut self, prep_instruction: ::models::PrepInstruction) {
    self.prep_instruction = prep_instruction;
  }

  pub fn with_prep_instruction(mut self, prep_instruction: ::models::PrepInstruction) -> PrepDetails {
    self.prep_instruction = prep_instruction;
    self
  }

  pub fn prep_instruction(&self) -> &::models::PrepInstruction {
    &self.prep_instruction
  }


  pub fn set_prep_owner(&mut self, prep_owner: ::models::PrepOwner) {
    self.prep_owner = prep_owner;
  }

  pub fn with_prep_owner(mut self, prep_owner: ::models::PrepOwner) -> PrepDetails {
    self.prep_owner = prep_owner;
    self
  }

  pub fn prep_owner(&self) -> &::models::PrepOwner {
    &self.prep_owner
  }


}



