/* 
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// TransportStatus : Indicates the status of the Amazon-partnered carrier shipment.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TransportStatus {
}

impl TransportStatus {
  /// Indicates the status of the Amazon-partnered carrier shipment.
  pub fn new() -> TransportStatus {
    TransportStatus {
    }
  }

}

// TODO enum 
// List of TransportStatus
//const (
//  
//  
//  
//)


