/* 
 * Selling Partner API for A+ Content Management
 *
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * OpenAPI spec version: 2020-11-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AsinBadge : A flag that provides additional information about an ASIN. This is contextual and may change depending on the request that generated it.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AsinBadge {
}

impl AsinBadge {
  /// A flag that provides additional information about an ASIN. This is contextual and may change depending on the request that generated it.
  pub fn new() -> AsinBadge {
    AsinBadge {
    }
  }

}

// TODO enum 
// List of AsinBadge
//const (
//  
//  
//  
//)


