/* 
 * Selling Partner API for A+ Content Management
 *
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * OpenAPI spec version: 2020-11-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ImageDimensions : The dimensions extending from the top left corner of the cropped image, or the top left corner of the original image if there is no cropping. Only `pixels` is allowed as the units value for ImageDimensions.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ImageDimensions {
  #[serde(rename = "width")]
  width: ::models::IntegerWithUnits,
  #[serde(rename = "height")]
  height: ::models::IntegerWithUnits
}

impl ImageDimensions {
  /// The dimensions extending from the top left corner of the cropped image, or the top left corner of the original image if there is no cropping. Only `pixels` is allowed as the units value for ImageDimensions.
  pub fn new(width: ::models::IntegerWithUnits, height: ::models::IntegerWithUnits) -> ImageDimensions {
    ImageDimensions {
      width: width,
      height: height
    }
  }

  pub fn set_width(&mut self, width: ::models::IntegerWithUnits) {
    self.width = width;
  }

  pub fn with_width(mut self, width: ::models::IntegerWithUnits) -> ImageDimensions {
    self.width = width;
    self
  }

  pub fn width(&self) -> &::models::IntegerWithUnits {
    &self.width
  }


  pub fn set_height(&mut self, height: ::models::IntegerWithUnits) {
    self.height = height;
  }

  pub fn with_height(mut self, height: ::models::IntegerWithUnits) -> ImageDimensions {
    self.height = height;
    self
  }

  pub fn height(&self) -> &::models::IntegerWithUnits {
    &self.height
  }


}



