/* 
 * Selling Partner API for A+ Content Management
 *
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * OpenAPI spec version: 2020-11-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// IntegerWithUnits : A whole number dimension and its unit of measurement. For example, this can represent 100 pixels.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IntegerWithUnits {
  /// The dimension value.
  #[serde(rename = "value")]
  value: i32,
  /// The unit of measurement.
  #[serde(rename = "units")]
  units: String
}

impl IntegerWithUnits {
  /// A whole number dimension and its unit of measurement. For example, this can represent 100 pixels.
  pub fn new(value: i32, units: String) -> IntegerWithUnits {
    IntegerWithUnits {
      value: value,
      units: units
    }
  }

  pub fn set_value(&mut self, value: i32) {
    self.value = value;
  }

  pub fn with_value(mut self, value: i32) -> IntegerWithUnits {
    self.value = value;
    self
  }

  pub fn value(&self) -> &i32 {
    &self.value
  }


  pub fn set_units(&mut self, units: String) {
    self.units = units;
  }

  pub fn with_units(mut self, units: String) -> IntegerWithUnits {
    self.units = units;
    self
  }

  pub fn units(&self) -> &String {
    &self.units
  }


}



