mod aplus_paginated_response;
pub use self::aplus_paginated_response::AplusPaginatedResponse;
mod aplus_response;
pub use self::aplus_response::AplusResponse;
mod asin;
pub use self::asin::Asin;
mod asin_badge;
pub use self::asin_badge::AsinBadge;
mod asin_badge_set;
pub use self::asin_badge_set::AsinBadgeSet;
mod asin_metadata;
pub use self::asin_metadata::AsinMetadata;
mod asin_metadata_set;
pub use self::asin_metadata_set::AsinMetadataSet;
mod asin_set;
pub use self::asin_set::AsinSet;
mod color_type;
pub use self::color_type::ColorType;
mod content_badge;
pub use self::content_badge::ContentBadge;
mod content_badge_set;
pub use self::content_badge_set::ContentBadgeSet;
mod content_document;
pub use self::content_document::ContentDocument;
mod content_metadata;
pub use self::content_metadata::ContentMetadata;
mod content_metadata_record;
pub use self::content_metadata_record::ContentMetadataRecord;
mod content_metadata_record_list;
pub use self::content_metadata_record_list::ContentMetadataRecordList;
mod content_module;
pub use self::content_module::ContentModule;
mod content_module_list;
pub use self::content_module_list::ContentModuleList;
mod content_module_type;
pub use self::content_module_type::ContentModuleType;
mod content_record;
pub use self::content_record::ContentRecord;
mod content_record_list;
pub use self::content_record_list::ContentRecordList;
mod content_reference_key;
pub use self::content_reference_key::ContentReferenceKey;
mod content_reference_key_set;
pub use self::content_reference_key_set::ContentReferenceKeySet;
mod content_status;
pub use self::content_status::ContentStatus;
mod content_sub_type;
pub use self::content_sub_type::ContentSubType;
mod content_type;
pub use self::content_type::ContentType;
mod decorator;
pub use self::decorator::Decorator;
mod decorator_set;
pub use self::decorator_set::DecoratorSet;
mod decorator_type;
pub use self::decorator_type::DecoratorType;
mod error;
pub use self::error::Error;
mod error_list;
pub use self::error_list::ErrorList;
mod get_content_document_included_data_type;
pub use self::get_content_document_included_data_type::GetContentDocumentIncludedDataType;
mod get_content_document_response;
pub use self::get_content_document_response::GetContentDocumentResponse;
mod image_component;
pub use self::image_component::ImageComponent;
mod image_crop_specification;
pub use self::image_crop_specification::ImageCropSpecification;
mod image_dimensions;
pub use self::image_dimensions::ImageDimensions;
mod image_offsets;
pub use self::image_offsets::ImageOffsets;
mod integer_with_units;
pub use self::integer_with_units::IntegerWithUnits;
mod language_tag;
pub use self::language_tag::LanguageTag;
mod list_content_document_asin_relations_included_data_type;
pub use self::list_content_document_asin_relations_included_data_type::ListContentDocumentAsinRelationsIncludedDataType;
mod list_content_document_asin_relations_response;
pub use self::list_content_document_asin_relations_response::ListContentDocumentAsinRelationsResponse;
mod marketplace_id;
pub use self::marketplace_id::MarketplaceId;
mod message_set;
pub use self::message_set::MessageSet;
mod page_token;
pub use self::page_token::PageToken;
mod paragraph_component;
pub use self::paragraph_component::ParagraphComponent;
mod plain_text_item;
pub use self::plain_text_item::PlainTextItem;
mod position_type;
pub use self::position_type::PositionType;
mod post_content_document_approval_submission_response;
pub use self::post_content_document_approval_submission_response::PostContentDocumentApprovalSubmissionResponse;
mod post_content_document_asin_relations_request;
pub use self::post_content_document_asin_relations_request::PostContentDocumentAsinRelationsRequest;
mod post_content_document_asin_relations_response;
pub use self::post_content_document_asin_relations_response::PostContentDocumentAsinRelationsResponse;
mod post_content_document_request;
pub use self::post_content_document_request::PostContentDocumentRequest;
mod post_content_document_response;
pub use self::post_content_document_response::PostContentDocumentResponse;
mod post_content_document_suspend_submission_response;
pub use self::post_content_document_suspend_submission_response::PostContentDocumentSuspendSubmissionResponse;
mod publish_record;
pub use self::publish_record::PublishRecord;
mod publish_record_list;
pub use self::publish_record_list::PublishRecordList;
mod search_content_documents_response;
pub use self::search_content_documents_response::SearchContentDocumentsResponse;
mod search_content_publish_records_response;
pub use self::search_content_publish_records_response::SearchContentPublishRecordsResponse;
mod standard_company_logo_module;
pub use self::standard_company_logo_module::StandardCompanyLogoModule;
mod standard_comparison_product_block;
pub use self::standard_comparison_product_block::StandardComparisonProductBlock;
mod standard_comparison_table_module;
pub use self::standard_comparison_table_module::StandardComparisonTableModule;
mod standard_four_image_text_module;
pub use self::standard_four_image_text_module::StandardFourImageTextModule;
mod standard_four_image_text_quadrant_module;
pub use self::standard_four_image_text_quadrant_module::StandardFourImageTextQuadrantModule;
mod standard_header_image_text_module;
pub use self::standard_header_image_text_module::StandardHeaderImageTextModule;
mod standard_header_text_list_block;
pub use self::standard_header_text_list_block::StandardHeaderTextListBlock;
mod standard_image_caption_block;
pub use self::standard_image_caption_block::StandardImageCaptionBlock;
mod standard_image_sidebar_module;
pub use self::standard_image_sidebar_module::StandardImageSidebarModule;
mod standard_image_text_block;
pub use self::standard_image_text_block::StandardImageTextBlock;
mod standard_image_text_caption_block;
pub use self::standard_image_text_caption_block::StandardImageTextCaptionBlock;
mod standard_image_text_overlay_module;
pub use self::standard_image_text_overlay_module::StandardImageTextOverlayModule;
mod standard_multiple_image_text_module;
pub use self::standard_multiple_image_text_module::StandardMultipleImageTextModule;
mod standard_product_description_module;
pub use self::standard_product_description_module::StandardProductDescriptionModule;
mod standard_single_image_highlights_module;
pub use self::standard_single_image_highlights_module::StandardSingleImageHighlightsModule;
mod standard_single_image_specs_detail_module;
pub use self::standard_single_image_specs_detail_module::StandardSingleImageSpecsDetailModule;
mod standard_single_side_image_module;
pub use self::standard_single_side_image_module::StandardSingleSideImageModule;
mod standard_tech_specs_module;
pub use self::standard_tech_specs_module::StandardTechSpecsModule;
mod standard_text_block;
pub use self::standard_text_block::StandardTextBlock;
mod standard_text_list_block;
pub use self::standard_text_list_block::StandardTextListBlock;
mod standard_text_module;
pub use self::standard_text_module::StandardTextModule;
mod standard_text_pair_block;
pub use self::standard_text_pair_block::StandardTextPairBlock;
mod standard_three_image_text_module;
pub use self::standard_three_image_text_module::StandardThreeImageTextModule;
mod text_component;
pub use self::text_component::TextComponent;
mod text_item;
pub use self::text_item::TextItem;
mod validate_content_document_asin_relations_response;
pub use self::validate_content_document_asin_relations_response::ValidateContentDocumentAsinRelationsResponse;

// TODO(farcaller): sort out files
pub struct File;
