/* 
 * Selling Partner API for A+ Content Management
 *
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * OpenAPI spec version: 2020-11-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// PlainTextItem : Plain positional text, used in collections of brief labels and descriptors.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PlainTextItem {
  /// The rank or index of this text item within the collection. Different items cannot occupy the same position within a single collection.
  #[serde(rename = "position")]
  position: i32,
  /// The actual plain text.
  #[serde(rename = "value")]
  value: String
}

impl PlainTextItem {
  /// Plain positional text, used in collections of brief labels and descriptors.
  pub fn new(position: i32, value: String) -> PlainTextItem {
    PlainTextItem {
      position: position,
      value: value
    }
  }

  pub fn set_position(&mut self, position: i32) {
    self.position = position;
  }

  pub fn with_position(mut self, position: i32) -> PlainTextItem {
    self.position = position;
    self
  }

  pub fn position(&self) -> &i32 {
    &self.position
  }


  pub fn set_value(&mut self, value: String) {
    self.value = value;
  }

  pub fn with_value(mut self, value: String) -> PlainTextItem {
    self.value = value;
    self
  }

  pub fn value(&self) -> &String {
    &self.value
  }


}



