/* 
 * Selling Partner API for A+ Content Management
 *
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * OpenAPI spec version: 2020-11-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// StandardProductDescriptionModule : Standard product description text.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct StandardProductDescriptionModule {
  #[serde(rename = "body")]
  body: ::models::ParagraphComponent
}

impl StandardProductDescriptionModule {
  /// Standard product description text.
  pub fn new(body: ::models::ParagraphComponent) -> StandardProductDescriptionModule {
    StandardProductDescriptionModule {
      body: body
    }
  }

  pub fn set_body(&mut self, body: ::models::ParagraphComponent) {
    self.body = body;
  }

  pub fn with_body(mut self, body: ::models::ParagraphComponent) -> StandardProductDescriptionModule {
    self.body = body;
    self
  }

  pub fn body(&self) -> &::models::ParagraphComponent {
    &self.body
  }


}



