/* 
 * Selling Partner API for A+ Content Management
 *
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * OpenAPI spec version: 2020-11-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// StandardTextModule : A standard headline and body text.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct StandardTextModule {
  #[serde(rename = "headline")]
  headline: Option<::models::TextComponent>,
  #[serde(rename = "body")]
  body: ::models::ParagraphComponent
}

impl StandardTextModule {
  /// A standard headline and body text.
  pub fn new(body: ::models::ParagraphComponent) -> StandardTextModule {
    StandardTextModule {
      headline: None,
      body: body
    }
  }

  pub fn set_headline(&mut self, headline: ::models::TextComponent) {
    self.headline = Some(headline);
  }

  pub fn with_headline(mut self, headline: ::models::TextComponent) -> StandardTextModule {
    self.headline = Some(headline);
    self
  }

  pub fn headline(&self) -> Option<&::models::TextComponent> {
    self.headline.as_ref()
  }

  pub fn reset_headline(&mut self) {
    self.headline = None;
  }

  pub fn set_body(&mut self, body: ::models::ParagraphComponent) {
    self.body = body;
  }

  pub fn with_body(mut self, body: ::models::ParagraphComponent) -> StandardTextModule {
    self.body = body;
    self
  }

  pub fn body(&self) -> &::models::ParagraphComponent {
    &self.body
  }


}



