/* 
 * Selling Partner API for A+ Content Management
 *
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * OpenAPI spec version: 2020-11-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// TextItem : Rich positional text, usually presented as a collection of bullet points.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TextItem {
  /// The rank or index of this text item within the collection. Different items cannot occupy the same position within a single collection.
  #[serde(rename = "position")]
  position: i32,
  #[serde(rename = "text")]
  text: ::models::TextComponent
}

impl TextItem {
  /// Rich positional text, usually presented as a collection of bullet points.
  pub fn new(position: i32, text: ::models::TextComponent) -> TextItem {
    TextItem {
      position: position,
      text: text
    }
  }

  pub fn set_position(&mut self, position: i32) {
    self.position = position;
  }

  pub fn with_position(mut self, position: i32) -> TextItem {
    self.position = position;
    self
  }

  pub fn position(&self) -> &i32 {
    &self.position
  }


  pub fn set_text(&mut self, text: ::models::TextComponent) {
    self.text = text;
  }

  pub fn with_text(mut self, text: ::models::TextComponent) -> TextItem {
    self.text = text;
    self
  }

  pub fn text(&self) -> &::models::TextComponent {
    &self.text
  }


}



