/* 
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct QualifiersType {
  /// The condition of the item. Possible values: New, Used, Collectible, Refurbished, or Club.
  #[serde(rename = "ItemCondition")]
  item_condition: String,
  /// The item subcondition for the offer listing. Possible values: New, Mint, Very Good, Good, Acceptable, Poor, Club, OEM, Warranty, Refurbished Warranty, Refurbished, Open Box, or Other.
  #[serde(rename = "ItemSubcondition")]
  item_subcondition: String,
  /// The fulfillment channel for the item. Possible values:  * Amazon - Fulfilled by Amazon. * Merchant - Fulfilled by the seller.
  #[serde(rename = "FulfillmentChannel")]
  fulfillment_channel: String,
  /// Indicates whether the marketplace specified in the request and the location that the item ships from are in the same country. Possible values: True, False, or Unknown.
  #[serde(rename = "ShipsDomestically")]
  ships_domestically: String,
  /// (0-2 days, 3-7 days, 8-13 days, or 14 or more days) – Indicates the maximum time within which the item will likely be shipped once an order has been placed.
  #[serde(rename = "ShippingTime")]
  shipping_time: ::models::ShippingTimeType,
  /// (98-100%, 95-97%, 90-94%, 80-89%, 70-79%, Less than 70%, or Just launched ) – Indicates the percentage of feedback ratings that were positive over the past 12 months.
  #[serde(rename = "SellerPositiveFeedbackRating")]
  seller_positive_feedback_rating: String
}

impl QualifiersType {
  pub fn new(item_condition: String, item_subcondition: String, fulfillment_channel: String, ships_domestically: String, shipping_time: ::models::ShippingTimeType, seller_positive_feedback_rating: String) -> QualifiersType {
    QualifiersType {
      item_condition: item_condition,
      item_subcondition: item_subcondition,
      fulfillment_channel: fulfillment_channel,
      ships_domestically: ships_domestically,
      shipping_time: shipping_time,
      seller_positive_feedback_rating: seller_positive_feedback_rating
    }
  }

  pub fn set_item_condition(&mut self, item_condition: String) {
    self.item_condition = item_condition;
  }

  pub fn with_item_condition(mut self, item_condition: String) -> QualifiersType {
    self.item_condition = item_condition;
    self
  }

  pub fn item_condition(&self) -> &String {
    &self.item_condition
  }


  pub fn set_item_subcondition(&mut self, item_subcondition: String) {
    self.item_subcondition = item_subcondition;
  }

  pub fn with_item_subcondition(mut self, item_subcondition: String) -> QualifiersType {
    self.item_subcondition = item_subcondition;
    self
  }

  pub fn item_subcondition(&self) -> &String {
    &self.item_subcondition
  }


  pub fn set_fulfillment_channel(&mut self, fulfillment_channel: String) {
    self.fulfillment_channel = fulfillment_channel;
  }

  pub fn with_fulfillment_channel(mut self, fulfillment_channel: String) -> QualifiersType {
    self.fulfillment_channel = fulfillment_channel;
    self
  }

  pub fn fulfillment_channel(&self) -> &String {
    &self.fulfillment_channel
  }


  pub fn set_ships_domestically(&mut self, ships_domestically: String) {
    self.ships_domestically = ships_domestically;
  }

  pub fn with_ships_domestically(mut self, ships_domestically: String) -> QualifiersType {
    self.ships_domestically = ships_domestically;
    self
  }

  pub fn ships_domestically(&self) -> &String {
    &self.ships_domestically
  }


  pub fn set_shipping_time(&mut self, shipping_time: ::models::ShippingTimeType) {
    self.shipping_time = shipping_time;
  }

  pub fn with_shipping_time(mut self, shipping_time: ::models::ShippingTimeType) -> QualifiersType {
    self.shipping_time = shipping_time;
    self
  }

  pub fn shipping_time(&self) -> &::models::ShippingTimeType {
    &self.shipping_time
  }


  pub fn set_seller_positive_feedback_rating(&mut self, seller_positive_feedback_rating: String) {
    self.seller_positive_feedback_rating = seller_positive_feedback_rating;
  }

  pub fn with_seller_positive_feedback_rating(mut self, seller_positive_feedback_rating: String) -> QualifiersType {
    self.seller_positive_feedback_rating = seller_positive_feedback_rating;
    self
  }

  pub fn seller_positive_feedback_rating(&self) -> &String {
    &self.seller_positive_feedback_rating
  }


}



