/* 
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// OrderItemBuyerInfoList : A single order item's buyer information list.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct OrderItemBuyerInfoList {
}

impl OrderItemBuyerInfoList {
  /// A single order item's buyer information list.
  pub fn new() -> OrderItemBuyerInfoList {
    OrderItemBuyerInfoList {
    }
  }

}



